FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o nimbuslb ./cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -o backend ./cmd/backend
RUN CGO_ENABLED=0 GOOS=linux go build -o public-demo ./cmd/public-demo

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/nimbuslb .
COPY --from=builder /app/backend .
COPY --from=builder /app/public-demo .
COPY configs ./configs

ENV NIMBUSLB_CONFIG=configs/config.public-demo.yaml

EXPOSE 8080

ENTRYPOINT ["./public-demo"]