FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -o backend ./cmd/backend

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/backend .

EXPOSE 9001 9002

ENTRYPOINT ["./backend"]